### ISSUE TITLE
Create templated, selectable subjective narratives.

### ISSUE THREAD

**Issue by ebegoli** [ebegoli/SynthNotes#6]
Implement this:  
https://github.com/ebegoli/SynthNotes/wiki#generation-of-narrative-from-examples-and-with-consistent-random-values

and specifically this template:  
https://github.com/ebegoli/SynthNotes/wiki#template  

with these variables:  
https://github.com/ebegoli/SynthNotes/wiki#template-variables  

An example of the populated template:  
https://github.com/ebegoli/SynthNotes/wiki#an-example-of-a-populated-template

**Comment by kbrown42** [comment]
Added some work towards this in my last two commits.  Some life stressors and patient statements are added and gender agreement throughout each note.
